### PR TITLE
Task2

### PR DESCRIPTION
**Pull request by MaksRoma**
Added 2 new projects: Client (c++) and Server (C), which represents HW <-> SW communication using UART

### CODE REVIEW

**Comment by andrii-s-spitzer-lpnu-ua** [comment]
remove all bineries files and add it under gitignore.

**Comment by MaksRoma** [comment]
all binaries are deleted, as i guess

**Comment by andrii-s-spitzer-lpnu-ua** [comment]
> all binaries are deleted, as i guess

not all:
image

**Comment by MaksRoma** [comment]
done

**Review by andrii-s-spitzer-lpnu-ua — APPROVED** [review]

**Pull request merged**
